import "../globals.css";

import type { Metadata } from "next";
import { SessionProvider } from "@/components";
import { getServerSession } from "next-auth";

export const metadata: Metadata = {
  title: "Agentic PMO",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  const session = await getServerSession();

  return (
    <html lang="en" className="dark">
      <body className="bg-background text-black dark:text-white">
        <SessionProvider session={session}>
          <main className="grid grid-cols-2 w-screen h-screen">{children}</main>
        </SessionProvider>
      </body>
    </html>
  );
}
