import "./globals.css";

import type { Metadata } from "next";

import SessionProvider from "../components/SessionProvider";
import Header from "../components/Header";
import Navbar from "../components/Navbar";
import { getServerSession } from "next-auth";

export const metadata: Metadata = {
  title: "Agentic PMO",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  const session = await getServerSession();

  return (
    <html lang="en" className="dark">
      <body className="bg-background text-black dark:text-white">
        <SessionProvider session={session}>
          <Header />
          <main className="grid grid-cols-[auto_1fr] max-h-content overflow-hidden">
            <Navbar />
            {children}
          </main>
        </SessionProvider>
      </body>
    </html>
  );
}
